use customer_behaviour;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender , SUM(purchase_amount) AS revenue from customer
GROUP BY GENDER;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount, discount_applied from customer 
where purchase_amount > (select AVG (purchase_amount) from customer) AND discount_applied = "Yes" ;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating),2) AS average_rating
FROM customer
GROUP BY item_purchased
order by average_rating DESC
limit 5 ;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
	shipping_type,
    AVG(purchase_amount)
FROM customer
    WHERE shipping_type IN ("Standard","Express")
	GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
	count(customer_id),
	subscription_status,
    AVG(purchase_amount) AS average_spending,
    SUM(purchase_amount) as total_revenue
FROM customer
	GROUP BY subscription_status;
    


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 
SELECT item_purchased,
       (100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of purchases, and show the count of each segment.
with customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
    FROM customer)
SELECT customer_segment , count(*) AS 'number of customer'
from customer_type
Group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely tosubscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

